gen-helloworld: protoc --go_out=. --go_opt=paths=source_relative .\helloworld\helloworld.proto
gen-helloworld-grpc: protoc --go-grpc_out=. --go-grpc_opt=paths=source_relative .\helloworld\helloworld.proto


gen-todolist: protoc --go_out=. --go_opt=paths=source_relative .\todolist\todolist.proto
gen-todolist-grpc: protoc --go-grpc_out=. --go-grpc_opt=paths=source_relative .\todolist\todolist.proto